  apiVersion: v1
  kind: Pod
  metadata:
    name: rsong-redis
  spec:
    containers:
    - name: redis
      image: kubernetes/redis:v1
      env:
      - name: MASTER
        value: "true"
      ports:
      - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
      - mountPath: /redis-master-data
        name: data
      - mountPath: /redis-master
        name: config
    volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: rsong-rsong-redis-config
        items:
        - key: rsong-redis-config
          path: redis.conf