apiVersion: v1
kind: Service
metadata:
  name: rnode
spec:
  ports:
  - port: 4000
    name: metrics
  - port: 5041
    name: grpc
  selector:
    app: rnode
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rnode
spec:
  selector:
    matchLabels:
      app: rnode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rnode
    spec:
      containers:
      - image: kayvank/rnode:0.6.1
        name: rnode
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
          name: metrics
        - containerPort: 5041
          name: grpc
          name: rnode
        volumeMounts:
        - name: rnode-persistent-storage
          mountPath: /var/lib/rnode
      volumes:
      - name: rnode-persistent-storage
        persistentVolumeClaim:
          claimName: rnode-pv-claim
