apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsong-proxy
  labels:
    app: rsong-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsong-proxy
  template:
    metadata:
      labels:
        app: rsong-proxy
    spec:
      containers:
      - name: rsong-proxy
        image: kayvank/rsong-proxy:1.0.7-SNAPSHOT-berlin-demo
        resources:
          requests:
            cpu: 100m
            memory: 20000m
        ports:
        - containerPort: 9000

