apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsong-proxy
  labels:
    app: rsong-proxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rsong-proxy
      tier: proxy
  template:
    metadata:
      labels:
        app: rsong-proxy
        tier: proxy
    spec:
      containers:
      - name: rsong-proxy
        image: kayvank/rsong-proxy:1.0.9-SNAPSHOT-v2-berlin-demo
        resources:
          requests:
            cpu: 100m
            memory: 20000m
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: GRPC_SERVER
          value: 35.231.97.153
        - name: GRPC_SERVER
          value: 35.231.97.153
        - name: REDIS_URL
          value: redis-master
        - name: HOST_URL
          value: http://35.235.93.121
        ports:
        - containerPort: 9000
